'use strict';
const fs=require('fs');const path=require('path');const cp=require('child_process');
const root=path.resolve(__dirname,'..');const dir=path.join(root,'games','spades');
const required=['index.html','styles.css','table-shell.css','table-cards.css','table-dialogs.css','responsive.css','game.js','game-core.js','game-play.js','game-match.js','game-init.js','platform.js','manifest.webmanifest','service-worker.js','icons/icon.svg'];
const fail=message=>{throw new Error(message)};required.forEach(file=>{if(!fs.existsSync(path.join(dir,file)))fail(`Missing ${file}`)});
['game.js','game-core.js','game-play.js','game-match.js','game-init.js','platform.js','service-worker.js'].forEach(file=>cp.execFileSync(process.execPath,['--check',path.join(dir,file)],{stdio:'inherit'}));
const index=fs.readFileSync(path.join(dir,'index.html'),'utf8');['styles.css','game.js','platform.js','manifest.webmanifest','service-worker.js'].forEach(file=>{if(!index.includes(file))fail(`index.html does not reference ${file}`)});
const loader=fs.readFileSync(path.join(dir,'game.js'),'utf8');['game-core.js','game-play.js','game-match.js','game-init.js'].forEach(file=>{if(!loader.includes(file))fail(`game.js does not load ${file}`)});
const platform=fs.readFileSync(path.join(dir,'platform.js'),'utf8');['/api/users','/api/battles','/api/bets'].forEach(endpoint=>{if(!platform.includes(endpoint))fail(`platform bridge missing ${endpoint}`)});if(/battles\/.+finish|settle.*spades|credit.*spades/i.test(platform))fail('Client must not settle local Spades results');
const sw=fs.readFileSync(path.join(dir,'service-worker.js'),'utf8');required.filter(file=>!['service-worker.js'].includes(file)).forEach(file=>{if(!sw.includes(file.replace('icons/','icons/')))fail(`service worker does not cache ${file}`)});
const htmlIds=[...index.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);const dup=htmlIds.find((id,i)=>htmlIds.indexOf(id)!==i);if(dup)fail(`Duplicate id ${dup}`);
console.log(`Spades validation passed: ${required.length} assets, ${htmlIds.length} unique IDs.`);
