'use strict';
const fs=require('fs');const path=require('path');const cp=require('child_process');const root=path.resolve(__dirname,'..'),dir=path.join(root,'games','spades');
const required=['index.html','styles.css','table-shell.css','table-cards.css','table-dialogs.css','responsive.css','game.js','game-core.js','game-play.js','game-match.js','game-init.js','platform.js','manifest.webmanifest','service-worker.js','icons/icon.svg'];const fail=m=>{throw new Error(m)};
function files(){required.forEach(file=>{if(!fs.existsSync(path.join(dir,file)))fail(`Missing ${file}`)});console.log(`Required files present: ${required.length}`)}
function syntax(){['game.js','game-core.js','game-play.js','game-match.js','game-init.js','platform.js','service-worker.js'].forEach(file=>cp.execFileSync(process.execPath,['--check',path.join(dir,file)],{stdio:'inherit'}));console.log('JavaScript syntax passed')}
function references(){const index=fs.readFileSync(path.join(dir,'index.html'),'utf8');['styles.css','game.js','platform.js','manifest.webmanifest','service-worker.js'].forEach(file=>{if(!index.includes(file))fail(`index.html does not reference ${file}`)});const loader=fs.readFileSync(path.join(dir,'game.js'),'utf8');['game-core.js','game-play.js','game-match.js','game-init.js'].forEach(file=>{if(!loader.includes(file))fail(`game.js does not load ${file}`)});const ids=[...index.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]),dup=ids.find((id,i)=>ids.indexOf(id)!==i);if(dup)fail(`Duplicate id ${dup}`);console.log(`References passed: ${ids.length} unique IDs`)}
function boundary(){const platform=fs.readFileSync(path.join(dir,'platform.js'),'utf8');if(!platform.includes('/api/battles'))fail('Practice predictions must read server-listed arenas');['/api/users','/api/bets','pay.html','Stripe'].forEach(forbidden=>{if(platform.includes(forbidden))fail(`Play-money integration contains forbidden real-wallet reference: ${forbidden}`)});if(!/no cash value|cannot be purchased/i.test(platform))fail('Play-money disclosure missing');if(/POST|method:\s*['"]POST/i.test(platform))fail('Practice prediction bridge must remain read-only to server APIs');console.log('Play-money boundary passed')}
function offline(){const sw=fs.readFileSync(path.join(dir,'service-worker.js'),'utf8');required.filter(file=>file!=='service-worker.js').forEach(file=>{if(!sw.includes(file))fail(`Service worker does not cache ${file}`)});console.log('Offline cache coverage passed')}
const gates={files,syntax,references,boundary,offline};const requested=process.argv[2];if(requested){if(!gates[requested])fail(`Unknown validation gate: ${requested}`);gates[requested]()}else{Object.values(gates).forEach(run=>run());console.log('Spades validation passed.')}
